### ISSUE TITLE
Temp sensor that reports target temp

### ISSUE THREAD

**Issue by DataFran** [chrisjshull/homebridge-nest#672]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to automate turning on my window AC units when I set the temperature on the Nest Thermostat. The limitation in Homekit is that it must be triggered by a sensor detecting something (or a device being controlled, Thermostats are not options in this list), so a temp sensor that reports the Target Temperature (which would change when the Nest is controlled either remotely or manually) could function as a trigger in an automation to turn on window AC units, mini splits, etc. 

**Describe the solution you'd like**
A new temperature sensor created by this plugin in HomeKit called "Nest Target Temperature" (or something similar, so it can be easily distinguished) which reports the current target temperature of the Nest thermostat.

**Describe alternatives you've considered**
I've tried to think of other ways to automate this using shortcuts, the problem is the limited number of triggers available in HomeKit, and none of the available options seem to do the job.

**Additional context**
I think this could be helpful for lots of people, turning multiple, individually controlled climate control units into what is basically fake central air.

**Comment by amomchilov** [comment]
You can synthesize your own templated temperature sensor in Home Assistant, and then expose that to HomeKit. You can do this all locally, without needing code-level changing in this package.

In `configuration.yaml`:

```yaml
sensor:
  - platform: template
    sensors:
      thermostat_setpoint:
        friendly_name: Thermostat setpoint
        device_class: temperature
        unit_of_measurement: °C # Or °F, or K
        value_template: state_attr("climate.living_room", "temperature")
#                                   ^^^^^^^^^^^^^^^^^^^ Your Nest thermostat ID here

# ...

homekit:
  - name: HA Bridge
    filter:
      include_entities:
        - sensor.thermostat_setpoint
        # ...
```
